# 标注了'FIXME'的是必须赋值的参数
# 标注了'CHANGED'的是可能需要修改的参数
# 标注了'NOTE'的是也许使用默认值即可的参数

sleep = 1

[opc]
opc_server_host = 'localhost'           # NOTE: OPC Server的hostname
opc_server_port = 7766                  # NOTE: OpenOPC Gateway的端口
opc_server_name = 'OPC.Server.name'     # FIXME: OPC Server名
opc_get_way = 'iproperties'             # NOTE: 取值方式，可选值为'iproperties', 'iread'
opc_tag_list = [                        # FIXME: OPC Server中的ITEM ID，即所采集的通道名
    'Group_1.Tag_1',
]

[socket]
protocol = 'udp'                        # CHANGED: 数据转发使用的协议
    [socket.tcp]
    tcp_host = '127.0.0.1'              # FIXME: 用于转发OPC数据的IP
    tcp_port = 8090                     # CHANGED: 用于转发OPC数据的Port
    [socket.udp]
    udp_host = '127.0.0.1'              # FIXME: 用来接收转发的OPC数据的IP
    udp_port = 8090                     # CHANGED: 用来接收转发的OPC数据的Port

[log]
console = true                          # CHANGED: 是否要将log输出到STDOUT，只在调试时有用，正式部署时需要关闭
console_level = 'DEBUG'                 # NOTE: 日志等级，可选值为'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
file = true                             # NOTE: 是否要将log输出到文件中
file_level = 'DEBUG'                    # NOTE: 日志等级，可选值为'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
log_file = 'logs/log.log'               # NOTE: log文件存储路径
max_size = 10240000                     # NOTE: 单个log文件大小，单位KB
backup_count = 5                        # NOTE: 最大log文件数
format_string = '(%(asctime)s), %(levelname)s, <%(threadName)s>, %(module)s, %(funcName)s, [%(lineno)d]: %(message)s'
